=== daiki91/xml-code/un.dtd
<!ELEMENT doc (livre* | article+)>
<!ELEMENT livre (titre, auteur+)>
<!ELEMENT article (titre, auteur+)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (nom, adresse)>
    <!ATTLIST auteur 
        id CDATA #REQUIRED>
<!ELEMENT nom (prenom, nomFamille)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT nomFamille (#PCDATA)>
<!ELEMENT adresse ANY>

=== daiki91/xml-code/get-dtd.xml
<?xml version='1.0' ?>
<!DOCTYPE doc SYSTEM './un.dtd'>

<doc>
    <article>
        <titre> Gigantomachia </titre>

        <auteur id="sss-c-s-h">
            <nom> 
              <prenom> Unknown </prenom>
                <nomFamille> Ranker </nomFamille>
            </nom>
            
            <adresse> Tower of nightmares </adresse>
        </auteur>
    
    </article>
</doc>
